version: '3'

services:

  # Backend
  backend-java:
    image: tinyurl-backend-java:latest
    ports:
      - 9002

  # Frontend
  frontend-nginx:
    image: tinyurl-frontend-nginx:latest
    ports:
      - 9001

  # Gateway
  gateway-nginx:
    image: tinyurl-gateway-nginx:latest
    ports:
      - 80:80

  # Riak
  riak-coordinator:
    image: basho/riak-kv
    ports:
      - 8087:8087
      - 8098:8098
    environment:
      - CLUSTER_NAME=riakkv
    labels:
      - 'com.basho.riak.cluster.name=riakkv'

  riak-member:
    image: basho/riak-kv
    ports:
      - 8087
      - 8098
    labels:
      - 'com.basho.riak.cluster.name=riakkv'
    links:
      - riak-coordinator
    depends_on:
      - riak-coordinator
    environment:
      - CLUSTER_NAME=riakkv
      - COORDINATOR_NODE=riak-coordinator

  # Zookeeper
  zookeeper:
    image: zookeeper:latest
    restart: always
    ports:
      - 2181:2181

  # Redis
  redis:
    image: redis:5-alpine

volumes:
  gradle:
