FROM nginx:alpine

# ARG host

ADD default.conf /etc/nginx/conf.d/

# RUN sed "s|%HOST%|$host|g" /etc/nginx/conf.d/default.conf.tpl > /etc/nginx/conf.d/default.conf
# RUN rm /etc/nginx/conf.d/default.conf.tpl
